services:

  postgres:
    image: postgres:16-alpine
    container_name: backend-postgres
    environment:
      #
      #Host name= postgres
      POSTGRES_DB: backend_T01 #=>Maintenance database
      POSTGRES_USER: admin_T01SA  #=>Username
      POSTGRES_PASSWORD: T01SA #=>Password
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: T01
    environment:
      PGADMIN_DEFAULT_EMAIL: T01SA@example.com  #ตอน login
      PGADMIN_DEFAULT_PASSWORD: T01SA  #ตอน login
    ports:
     - "8081:80"
    volumes:
     - pgadmin_data:/var/lib/pgadmin
    depends_on:
     - postgres
    restart: unless-stopped
    

volumes:
  postgres_data:
  pgadmin_data:
