import type { Concert } from '@/interface/IConcertInterface'
import { celestial, flux, pulse, starlight, come1, come2, come5 } from '@/assets/posters'

export const mockConcerts: Concert[] = [
  {
    id: 'neon-flux',
    title: 'Neon Flux Festival 2024',
    posterUrl: flux,
    bannerUrl: '/banners/neonFlux.jpg',
    featured: true,
    showStartDate: '2024-01-16',
    showEndDate: '2024-01-18',
    showTimeLabel: '17.00 น.',
    saleStartDate: '2023-12-01',
    saleEndDate: '2024-01-15',
    venue: 'Metroplex Arena',
    venueFloor: 'ฮอลล์ 1',
    province: 'กรุงเทพมหานคร',
    tiers: [
      { name: 'VIP', price: 5000 },
      { name: 'Standard', price: 3500 },
      { name: 'Economy', price: 2000 },
    ],
    saleStatus: 'on_sale',
    description:
      'เทศกาลดนตรีอิเล็กทรอนิกส์ 3 วันเต็ม รวมศิลปินไทยและต่างประเทศกว่า 20 วง พร้อมเวทีแสงสีเต็มรูปแบบ',
  },
  {
    id: 'neon-pulse',
    title: 'Neon Pulse',
    posterUrl: pulse,
    bannerUrl: '/banners/neonPulse.png',
    featured: true,
    showStartDate: '2024-02-28',
    showEndDate: '2024-02-28',
    showTimeLabel: '18.00 น.',
    saleStartDate: '2024-02-01',
    saleEndDate: '2024-02-15',
    venue: 'The Mall Korat',
    venueFloor: 'ชั้น 3',
    province: 'นครราชสีมา',
    tiers: [
      { name: 'Zone A', price: 2500 },
      { name: 'Zone B', price: 2000 },
      { name: 'Zone C', price: 1500 },
      { name: 'Zone D', price: 1000 },
    ],
    saleStatus: 'on_sale',
    description:
      'คอนเสิร์ตเดี่ยวเต็มรูปแบบครั้งแรกในภาคอีสาน เก็บทุกเพลงฮิตไว้ในค่ำคืนเดียว พร้อมวงดนตรีสดเต็มวง',
  },
  {
    id: 'celestial-sounds',
    title: 'Celestial Sounds',
    posterUrl: celestial,
    bannerUrl: '/banners/celestialSounds.jpg',
    featured: true,
    showStartDate: '2024-03-26',
    showEndDate: '2024-03-26',
    showTimeLabel: '19.00 น.',
    saleStartDate: '2024-02-20',
    saleEndDate: '2024-03-20',
    venue: 'Chiang Mai Hall',
    venueFloor: 'ชั้น 2',
    province: 'เชียงใหม่',
    tiers: [
      { name: 'Front', price: 3000 },
      { name: 'Middle', price: 2200 },
      { name: 'Back', price: 1200 },
    ],
    saleStatus: 'on_sale',
    description:
      'ค่ำคืนของดนตรีแอมเบียนต์และอิเล็กทรอนิกส์ใต้แสงดาว บรรยากาศสบาย ๆ เหมาะกับการมาเป็นกลุ่มเพื่อน',
  },
  {
    id: 'starlight-festival',
    title: 'Starlight Festival',
    posterUrl: starlight,
    bannerUrl: '/banners/starlightFestival.jpg',
    featured: true,
    showStartDate: '2024-04-23',
    showEndDate: '2024-04-25',
    showTimeLabel: '16.00 น.',
    saleStartDate: '2024-03-01',
    saleEndDate: '2024-04-20',
    venue: 'Khon Kaen Open Air',
    venueFloor: 'ลานกลางแจ้ง',
    province: 'ขอนแก่น',
    tiers: [
      { name: 'VIP', price: 4200 },
      { name: 'Standard', price: 2800 },
      { name: 'Economy', price: 1500 },
    ],
    saleStatus: 'on_sale',
    description:
      'ลดนตรีกลางแจ้ง 3 วัน 3 เวที พร้อมโซนอาหารและตลาดงานคราฟต์ตลอดงาน',
  },
  {
    id: 'coming-soon-1',
    title: 'Coming Soon 1',
    posterUrl: come1,
    bannerUrl: '/banners/neonFlux.jpg',
    featured: false,
    showStartDate: '2024-05-01',
    showEndDate: '2024-05-31',
    showTimeLabel: 'รอประกาศ',
    saleStartDate: '2024-05-01',
    saleEndDate: '2024-05-31',
    venue: 'รอประกาศ',
    venueFloor: 'รอประกาศ',
    province: 'รอประกาศ',
    tiers: [],
    saleStatus: 'coming_soon',
    description: 'งานคอนเสิร์ตเร็ว ๆ นี้ รายละเอียดจะประกาศให้ทราบอีกครั้ง',
  },
  {
    id: 'coming-soon-2',
    title: 'Coming Soon 2',
    posterUrl: come2,
    bannerUrl: '/banners/neonPulse.png',
    featured: false,
    showStartDate: '2024-05-01',
    showEndDate: '2024-05-31',
    showTimeLabel: 'รอประกาศ',
    saleStartDate: '2024-05-01',
    saleEndDate: '2024-05-31',
    venue: 'รอประกาศ',
    venueFloor: 'รอประกาศ',
    province: 'รอประกาศ',
    tiers: [],
    saleStatus: 'coming_soon',
    description: 'งานคอนเสิร์ตเร็ว ๆ นี้ รายละเอียดจะประกาศให้ทราบอีกครั้ง',
  },
  {
    id: 'coming-soon-3',
    title: 'Coming Soon 3',
    posterUrl: come5,
    bannerUrl: '/banners/celestialSounds.jpg',
    featured: false,
    showStartDate: '2024-05-01',
    showEndDate: '2024-05-31',
    showTimeLabel: 'รอประกาศ',
    saleStartDate: '2024-05-01',
    saleEndDate: '2024-05-31',
    venue: 'รอประกาศ',
    venueFloor: 'รอประกาศ',
    province: 'รอประกาศ',
    tiers: [],
    saleStatus: 'coming_soon',
    description: 'งานคอนเสิร์ตเร็ว ๆ นี้ รายละเอียดจะประกาศให้ทราบอีกครั้ง',
  },
]
